In [2]:
import torch

x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


In [3]:
x = torch.zeros([2,5])
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [4]:
x.shape

torch.Size([2, 5])

In [5]:
y = torch.rand([2,5])

In [6]:
y

tensor([[0.3466, 0.2489, 0.1895, 0.1128, 0.4850],
        [0.2016, 0.0100, 0.8016, 0.0496, 0.8463]])

In [7]:
y.view([1,10])

tensor([[0.3466, 0.2489, 0.1895, 0.1128, 0.4850, 0.2016, 0.0100, 0.8016, 0.0496,
         0.8463]])

In [8]:
y

tensor([[0.3466, 0.2489, 0.1895, 0.1128, 0.4850],
        [0.2016, 0.0100, 0.8016, 0.0496, 0.8463]])

In [9]:
y_new = y.view([1,10])

In [10]:
y_new

tensor([[0.3466, 0.2489, 0.1895, 0.1128, 0.4850, 0.2016, 0.0100, 0.8016, 0.0496,
         0.8463]])